Q3
In C++, a try-catch block is used to handle exceptions that are thrown within the try block. 
The catch block contains the code that will be executed when an exception is caught.
The exception is caught by the catch block that is able to handle the type of exception that was thrown.

A try-throw-catch block is similar, but it also includes a throw statement within the try block.
The throw statement is used to explicitly throw an exception, which can then be caught by the catch block.
The catch block can handle the specific exception that was thrown.

In general, try-catch block is used to handle errors, while try-throw-catch block is used to handle errors and also to throw errors explicitly.
